### PR TITLE
add methods to read binary .pb

### PR DESCRIPTION
**Pull request by freedomtan**
With this I can classify image using pretrained TensorFlow
classifier models. See my example program [here](https://github.com/freedomtan/label_image_for_Pharo_TensorFlow_CAPI_binding/blob/master/label_image.st)

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Thank you very much for your contribution 👍 
Maybe you can commit your example in the repository also ?

**Comment by freedomtan** [comment]
Sure, I will rewrite the example to be more generic and add documentation. Then I'll send PR.

**Comment by SergeStinckwich** [comment]
Thank you very much for your work !
What is your interests for using Pharo in ML ?

**Comment by Ducasse** [comment]
Welcome freedomtan and thanks.
What you should know is that we are a bunch of dynamic language lovers and in particular Pharo. So have look :) http://www.pharo.org 
Now Pharo is not the end of the story just the start because we want to reinvent Smalltalk :). Just that :).
You can reach us on discord ( https://discord.gg/QewZMZa )
Have fun.

**Comment by SergeStinckwich** [comment]
This is great if you can participate to the Pharo TensorFlow binding. There is still a lot to do.
We still have problems when we release memory. Like Stéphane say, you can join us the polymath channel on discord if you want.

**Comment by freedomtan** [comment]
@Ducasse Thanks. I enjoy reading your books 👍

**Comment by Ducasse** [comment]
Tx :) At least I got readers :)

**Pull request merged**
